import React, { createContext, useContext, useEffect, useState } from 'react';
import { supabase } from '../lib/supabase';

const AuthContext = createContext({});

export const AuthProvider = ({ children }) => {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  const fetchProfileAndSetUser = async (dbUser) => {
    if (!dbUser) {
      setUser(null);
      setLoading(false);
      return;
    }
    // Fetch the attached profile rows generated by our SQL trigger
    const { data } = await supabase.from('profiles').select('role, family_name').eq('id', dbUser.id).single();
    if (data) {
      setUser({ ...dbUser, role: data.role, family_name: data.family_name });
    } else {
      setUser(dbUser);
    }
    setLoading(false);
  };

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      fetchProfileAndSetUser(session?.user ?? null);
    });

    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (event === 'SIGNED_OUT') {
        setUser(null);
      } else if (session?.user) {
        fetchProfileAndSetUser(session.user);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  // Expose setUser directly for the Mock Login bypass logic
  return (
    <AuthContext.Provider value={{ user, setUser, loading }}>
      {!loading && children}
    </AuthContext.Provider>
  );
};

export const useAuth = () => {
  return useContext(AuthContext);
};
